### PR TITLE
Enable encoding of Maven registries.

### LINKED ISSUE #208: Proposal: Supporting Maven registries
The current Maven ecosystem definition is "The Maven Java package ecosystem. The name field is a Maven package name.", which is a little vague. 

We should clarify that this is referring to Maven Central by default, and if a different registry is required, allow the ecosystem to be "Maven:<repository URL>", similar to the Linux distro definitions (e.g. "Debian:7").

The default (Maven Central) should always be used/preferred where it makes sense.

### PR DESCRIPTION
**Pull request by oliverchang**
Fixes #208.

### CODE REVIEW

**Comment by oliverchang** [comment]
@darakian @cuixq for review as well.

**Comment by cuixq** [comment]
LGTM!

**Review by chrisbloom7 — APPROVED** [review]
❤️

**Comment by oliverchang** [comment]
Thanks @cuixq and @chrisbloom7 :) 

@darakian do you have any comments on this? Wanted to hear your thoughts also.

**Comment by darakian** [comment]
@oliverchang, sorry for the delay. My only comment is that I think it's worth adding a fully formed example for an alternate registry. Using the first artifact I see on `maven.google.com`; I believe this could be 
`Maven:maven.google.com/android.arch.core:common`

Otherwise, looks good to me 👍

**Comment by oliverchang** [comment]
> @oliverchang, sorry for the delay. My only comment is that I think it's worth adding a fully formed example for an alternate registry. Using the first artifact I see on `maven.google.com`; I believe this could be `Maven:maven.google.com/android.arch.core:common`
> 
> Otherwise, looks good to me 👍

Thanks! Hm, the group ID / artifact ID is not part of the ecosystem string here. It's instead part of  the `name` field. Perhaps I could clarify that the `name` is in the `groupID:artifactID` format ?

**Pull request merged**
