### PR TITLE
docs(osv-linter): Add a README.md

### PR DESCRIPTION
**Pull request by andrewpollock**
This commit adds a README.md to provide interested parties with some further details and guidance about the OSV linter

### CODE REVIEW

**Comment by andrewpollock** [comment]
@hogo6002 could you please also take a look at this and see how it reads for you as someone new to this?

**Comment by andrewpollock** [comment]
@darakian I'd appreciate your perspective on the readability of this, if you have time

**Comment by hogo6002** [comment]
> @hogo6002 could you please also take a look at this and see how it reads for you as someone new to this?

LGTM! The `Usage` and `Contributing` sections are very helpful for new contributors like me.

**Comment by andrewpollock** [comment]
@oliverchang I'd like to get this merged today, so any feedback from @darakian I'll act on in a follow-up PR.

**Comment by darakian** [comment]
Looks quite readable to me, but two things come to mind
1. Install instructions would be nice. I know clone & compile is implicit given that it's a git repo , but if the `go get <url>` method of installation works then I would call that out specifically. If it doesn't work then getting it to work would be nice :)
2. Breaking the checks out into their own section with some prose describing what they do would be nice. Maybe more relevant once there are more than six checks.

**Review by oliverchang — APPROVED** [review]
apologies, missed your earlier comment @andrewpollock!

**Pull request merged**
