### PR TITLE
Add links to OpenSSF Vulnerabilities Disclosures WG

### PR DESCRIPTION
**Pull request by david-a-wheeler**
We always want projects/SIGs to point to their working group, but this one doesn't. Let's fix that, and tweak some other text along the way so it's clearer for visitors.

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
@SecurityCRob @dlorenc - seem correct? I want to make sure we have links to the relevant WG.

**Review by oliverchang — APPROVED** [review]

**Review by Billywildhig — APPROVED** [review]

**Comment by oliverchang** [comment]
> @SecurityCRob @dlorenc - seem correct? I want to make sure we have links to the relevant WG.

friendly ping on this!

**Review by puerco — APPROVED** [review]
LGTM

**Review by SecurityCRob — APPROVED** [review]

**Comment by SecurityCRob** [comment]
+1

**Comment by oliverchang** [comment]
Thanks all!

**Pull request merged**
