### PR TITLE
Added INTRODUCED to compliment FIX

### PR DESCRIPTION
**Pull request by kurtseifried**
As per https://github.com/ossf/osv-schema/issues/125#issuecomment-1486206362

### CODE REVIEW

**Comment by kurtseifried** [comment]
Also can you cut a 1.4.1 release with this? I need this ASAP to convert all our Linux Kernel entries to 1.4.1 (with INTRODUCED in the URLs which 90% have or so)

**Comment by oliverchang** [comment]
> Also can you cut a 1.4.1 release with this? I need this ASAP to convert all our Linux Kernel entries to 1.4.1 (with INTRODUCED in the URLs which 90% have or so)

Will do, once we get this merged. Just waiting for a second approval from @chrisbloom7 :)

**Comment by joshbuker** [comment]
Fixes #125

**Comment by joshbuker** [comment]
Also, the next version should be `1.5.0` (rather than `1.4.1`) as these changes introduce new features.

**Review by chrisbloom7 — APPROVED** [review]

**Pull request merged**
